name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{matrix.env.os}} ${{matrix.env.name || matrix.env.c}} ${{matrix.env.modules && 'cppm' || 'cpp'}}-${{matrix.standard}}
    runs-on: ${{matrix.env.os}}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        env: [
          { os: ubuntu-22.04, cxx: g++-10,     arch: x64, gen: Ninja },
          { os: ubuntu-22.04, cxx: g++-11,     arch: x64, gen: Ninja },
          { os: ubuntu-22.04, cxx: clang++-13, arch: x64, gen: Ninja },
          { os: ubuntu-22.04, cxx: clang++-14, arch: x64, gen: Ninja },
          { os: ubuntu-22.04, cxx: clang++-15, arch: x64, gen: Ninja },
              
          { os: ubuntu-24.04, cxx: g++-12,     arch: x64, gen: Ninja },
          { os: ubuntu-24.04, cxx: g++-13,     arch: x64, gen: Ninja },
          { os: ubuntu-24.04, cxx: g++-14,     arch: x64, gen: Ninja },
          { os: ubuntu-24.04, cxx: clang++-16, arch: x64, gen: Ninja },
          { os: ubuntu-24.04, cxx: clang++-17, arch: x64, gen: Ninja },
          { os: ubuntu-24.04, cxx: clang++-18, arch: x64, gen: Ninja },
        ]
        # exclude:
        #   - env:
        #     TODO

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        submodules: recursive

    # - name: Setup modules (CMake, Ninja)
    #   if: matrix.env.modules && contains(matrix.env.gen, 'Ninja')
    #   uses: lukka/get-cmake@latest
    #   with:
    #     cmakeVersion: 4.1.2
    #     ninjaVersion: latest
    # - name: Setup libc
    #   if: matrix.env.modules && contains(matrix.env.os, 'ubuntu')
    #   run: sudo apt install libc++-dev libc++abi-dev
    # - name: Setup clang and fix 'import std'
    #   if: matrix.env.modules && contains(matrix.env.os, 'macos')
    #   run: |
    #     brew install llvm
    #     CMAKE_FIX=`which cmake`
    #     CMAKE_FIX="`dirname $CMAKE_FIX`/../share/cmake-4.1/Modules/Compiler/Clang-CXX-CXXImportStd.cmake"
    #     sed -i '' 's|\${_clang_modules_json_impl}.modules.json|/opt/homebrew/opt/llvm/lib/c++/libc++.modules.json|g' $CMAKE_FIX # https://gitlab.kitware.com/cmake/cmake/-/issues/25965#note_1523575

    - name: Setup MSVC
      if: matrix.env.name == 'msvc' && contains(matrix.env.os, 'windows')
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: ${{matrix.env.arch}}

    - name: Setup Ubuntu
      if: matrix.env.os == 'ubuntu-22.04' || matrix.env.os == ubuntu-24.04
      run: sudo apt update && sudo apt install libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

    - name: Generate Headers
      run: |
        cmake -B build -G ${{matrix.env.gen}}          \
          -D VULKAN_HPP_GENERATOR_BUILD=ON             \
          -D VULKAN_HPP_RUN_GENERATOR=OFF              \
          -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
          -D VULKAN_HPP_TESTS_BUILD=OFF                \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
          -D VULKAN_HPP_PRECOMPILE=OFF                 \
          -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}    \
          -D CMAKE_CXX_STANDARD=20                     \
          -D CMAKE_BUILD_TYPE=Debug
        cmake --build build --parallel

        cmake -B build -G ${{matrix.env.gen}} --fresh  \
          -D VULKAN_HPP_GENERATOR_BUILD=ON             \
          -D VULKAN_HPP_RUN_GENERATOR=ON               \
          -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
          -D VULKAN_HPP_TESTS_BUILD=OFF                \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
          -D VULKAN_HPP_PRECOMPILE=OFF                 \
          -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}    \
          -D CMAKE_CXX_STANDARD=20                     \
          -D CMAKE_BUILD_TYPE=Release
        cmake --build build --parallel --clean-first
    
    - name: Build Samples with C++23
      run: |
        cmake -B build -G ${{matrix.env.gen}}             \
          -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
          -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
          -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
          -D VULKAN_HPP_TESTS_BUILD=OFF                   \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
          -D VULKAN_HPP_PRECOMPILE=OFF                    \
          -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}       \
          -D CMAKE_CXX_STANDARD=23                        \
          -D CMAKE_BUILD_TYPE=Debug
        cmake --build build --parallel

        cmake -B build -G ${{matrix.env.gen}} --fresh     \
          -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
          -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
          -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
          -D VULKAN_HPP_TESTS_BUILD=OFF                   \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
          -D VULKAN_HPP_PRECOMPILE=OFF                    \
          -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}       \
          -D CMAKE_CXX_STANDARD=23                        \
          -D CMAKE_BUILD_TYPE=Release
        cmake --build build --parallel --clean-first

    - name: Build Tests with C++11 to C++23 # TODO: 11 to 23
      run: |
        for CXX_STANDARD in 11; do
          for BUILD_TYPE in Debug Release; do
          
            if [ ${{matrix.env.cxx}} == clang++-17 ] && [ $CXX_STANDARD == 23 ]; then
              continue
            fi

            echo "================================================================================="
            echo "Building C++$CXX_STANDARD in $BUILD_TYPE"
            echo "================================================================================="

            cmake -B build -G ${{matrix.env.gen}} --fresh     \
              -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
              -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
              -D VULKAN_HPP_SAMPLES_BUILD=OFF                 \
              -D VULKAN_HPP_TESTS_BUILD=ON                    \
              -D VULKAN_HPP_TESTS_CTEST=ON                    \
              -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
              -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
              -D VULKAN_HPP_PRECOMPILE=OFF                    \
              -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}       \
              -D CMAKE_CXX_STANDARD=$CXX_STANDARD             \
              -D CMAKE_BUILD_TYPE=$BUILD_TYPE
            ctest -j --output-on-failure --test-dir build -C $BUILD_TYPE
          done
        done


