name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{matrix.env.os}} ${{matrix.env.arch}}, ${{matrix.env.gen}}, ${{matrix.env.cxx}} ${{matrix.env.modules && '[modules]' || ''}}
    runs-on: ${{matrix.env.os}}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        env: [
          # { os: macos-14,     cxx: clang++,    arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: macos-15,     cxx: clang++,    arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: macos-26,     cxx: clang++,    arch: x64, gen: Ninja,                 cxx-max: 23 },

          # { os: ubuntu-22.04, cxx: g++-10,     arch: x64, gen: Ninja,                 cxx-max: 17 },
          # { os: ubuntu-22.04, cxx: g++-11,     arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: ubuntu-22.04, cxx: clang++-13, arch: x64, gen: Ninja,                 cxx-max: 20 },
          # { os: ubuntu-22.04, cxx: clang++-14, arch: x64, gen: Ninja,                 cxx-max: 20 },
          # { os: ubuntu-22.04, cxx: clang++-15, arch: x64, gen: Ninja,                 cxx-max: 20 },

          # { os: ubuntu-24.04, cxx: g++-12,     arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: ubuntu-24.04, cxx: g++-13,     arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: ubuntu-24.04, cxx: g++-14,     arch: x64, gen: Ninja,                 cxx-max: 23 },
          # { os: ubuntu-24.04, cxx: clang++-16, arch: x64, gen: Ninja,                 cxx-max: 20 },
          # { os: ubuntu-24.04, cxx: clang++-17, arch: x64, gen: Ninja,                 cxx-max: 20 },
          # { os: ubuntu-24.04, cxx: clang++-18, arch: x64, gen: Ninja,                 cxx-max: 23 },

          # { os: windows-2022, cxx: c++,        arch: x86, gen: Visual Studio 17 2022, cxx-max: 23 },
          # { os: windows-2022, cxx: c++,        arch: x64, gen: Visual Studio 17 2022, cxx-max: 23 },
          # { os: windows-2022, cxx: clang-cl,   arch: x64, gen: Ninja,                 cxx-max: 23 },

          # { os: windows-2025, cxx: c++,        arch: x86, gen: Visual Studio 17 2022, cxx-max: 23 },
          # { os: windows-2025, cxx: c++,        arch: x64, gen: Visual Studio 17 2022, cxx-max: 23 },
          # { os: windows-2025, cxx: clang-cl,   arch: x64, gen: Ninja,                 cxx-max: 23 },

          # { os: macos-26,     cxx: /opt/homebrew/opt/llvm/bin/clang++, arch: x64, gen: Ninja, cxx-max: 23, modules: true },
          # { os: ubuntu-24.04, cxx: clang++-18, arch: x64, gen: Ninja, cxx-max: 23, modules: true },
          { os: windows-2025, cxx: clang-cl,   arch: x64, gen: Ninja, cxx-max: 23, modules: true },
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        submodules: recursive

    - name: Setup Ubuntu
      if: contains(matrix.env.os, 'ubuntu')
      run: sudo apt update && sudo apt install libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev
    - name: Setup MacOS
      if: contains(matrix.env.os, 'macos')
      run: brew install clang-format molten-vk
    - name: Setup Windows (MSVC)
      if: matrix.env.cxx == 'c++' && contains(matrix.env.os, 'windows')
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: ${{matrix.env.arch}}

    - name: Setup Modules (CMake, Ninja)
      if: matrix.env.modules && contains(matrix.env.gen, 'Ninja')
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.1.2
        ninjaVersion: latest
    - name: Setup Modules (Ubuntu)
      if: matrix.env.modules && contains(matrix.env.os, 'ubuntu')
      run: sudo apt install libc++-dev libc++abi-dev
    - name: Setup Modules (MacOS)
      if: matrix.env.modules && contains(matrix.env.os, 'macos')
      run: |
        brew install llvm
        CMAKE_FIX=`which cmake`
        CMAKE_FIX="`dirname $CMAKE_FIX`/../share/cmake-4.1/Modules/Compiler/Clang-CXX-CXXImportStd.cmake"
        sed -i '' 's|\${_clang_modules_json_impl}.modules.json|/opt/homebrew/opt/llvm/lib/c++/libc++.modules.json|g' $CMAKE_FIX # https://gitlab.kitware.com/cmake/cmake/-/issues/25965#note_1523575

    # - name: Install glm, glfw and glslang
    #   if: (!matrix.env.modules && !contains(matrix.env.os, 'windows'))
    #   run: |
    #     cd glm
    #     cmake -B build -G '${{matrix.env.gen}}'      \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}  \
    #       -D CMAKE_CXX_STANDARD=11                   \
    #       -D CMAKE_BUILD_TYPE=Release                \
    #       -D GLM_BUILD_LIBRARY=ON                    \
    #       -D GLM_BUILD_INSTALL=ON                    \
    #       -D GLM_BUILD_TESTS=OFF
    #     cmake --build build --parallel
    #     sudo cmake --install build --config Release

    #     cd ../glfw
    #     cmake -B build -G '${{matrix.env.gen}}'      \
    #       -D CMAKE_BUILD_TYPE=Release                \
    #       -D GLFW_BUILD_EXAMPLES=OFF                 \
    #       -D GLFW_BUILD_TESTS=OFF                    \
    #       -D GLFW_BUILD_DOCS=OFF                     \
    #       -D GLFW_INSTALL=ON
    #     cmake --build build --parallel
    #     sudo cmake --install build --config Release

    #     cd ../glslang
    #     cmake -B build -G '${{matrix.env.gen}}'      \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}  \
    #       -D CMAKE_CXX_STANDARD=11                   \
    #       -D CMAKE_BUILD_TYPE=Release                \
    #       -D ENABLE_OPT=OFF                          \
    #       -D GLSLANG_TESTS_DEFAULT=OFF               \
    #       -D GLSLANG_ENABLE_INSTALL_DEFAULT=ON
    #     cmake --build build --parallel
    #     sudo cmake --install build --config Release
    #     cd ..

    # - name: Generate Headers with C++20
    #   run: |
    #     cmake -B build -G '${{matrix.env.gen}}'        \
    #       -D VULKAN_HPP_GENERATOR_BUILD=ON             \
    #       -D VULKAN_HPP_RUN_GENERATOR=OFF              \
    #       -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
    #       -D VULKAN_HPP_TESTS_BUILD=OFF                \
    #       -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON     \
    #       -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
    #       -D VULKAN_HPP_PRECOMPILE=OFF                 \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}    \
    #       -D CMAKE_CXX_STANDARD=20                     \
    #       -D CMAKE_BUILD_TYPE=Debug
    #     cmake --build build --parallel --config Debug

    #     cmake -B build -G '${{matrix.env.gen}}' --fresh \
    #       -D VULKAN_HPP_GENERATOR_BUILD=ON              \
    #       -D VULKAN_HPP_RUN_GENERATOR=ON                \
    #       -D VULKAN_HPP_SAMPLES_BUILD=OFF               \
    #       -D VULKAN_HPP_TESTS_BUILD=OFF                 \
    #       -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON      \
    #       -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON  \
    #       -D VULKAN_HPP_PRECOMPILE=OFF                  \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}     \
    #       -D CMAKE_CXX_STANDARD=20                      \
    #       -D CMAKE_BUILD_TYPE=Release
    #     cmake --build build --parallel --config Release --clean-first
    
    # - name: Build Samples with C++${{matrix.env.cxx-max}}
    #   if: (!matrix.env.modules)
    #   run: |
    #     cmake -B build -G '${{matrix.env.gen}}'           \
    #       -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
    #       -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
    #       -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
    #       -D VULKAN_HPP_TESTS_BUILD=OFF                   \
    #       -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
    #       -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
    #       -D VULKAN_HPP_PRECOMPILE=OFF                    \
    #       -D CMAKE_C_COMPILER=${{matrix.env.cxx}}         \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}       \
    #       -D CMAKE_CXX_STANDARD=${{matrix.env.cxx-max}}   \
    #       -D CMAKE_BUILD_TYPE=Debug
    #     cmake --build build --parallel --config Release

    #     cmake -B build -G '${{matrix.env.gen}}' --fresh   \
    #       -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
    #       -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
    #       -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
    #       -D VULKAN_HPP_TESTS_BUILD=OFF                   \
    #       -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
    #       -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
    #       -D VULKAN_HPP_PRECOMPILE=OFF                    \
    #       -D CMAKE_C_COMPILER=${{matrix.env.cxx}}         \
    #       -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}       \
    #       -D CMAKE_CXX_STANDARD=${{matrix.env.cxx-max}}   \
    #       -D CMAKE_BUILD_TYPE=Release
    #     cmake --build build --parallel --config Debug --clean-first

    - name: Build Tests with C++11 to C++${{matrix.env.cxx-max}}
      run: |
        for CXX_STANDARD in 11 14 17 20 23; do
          for BUILD_TYPE in Debug Release; do
            if [ $CXX_STANDARD -ge ${{matrix.env.cxx-max}} ]; then
              continue
            fi

            if [ $CXX_STANDARD -lt 23 ] && [ ${{matrix.env.modules && true || false}} ]; then
              continue
            fi
          
            echo "================================================================================="
            echo "Building C++$CXX_STANDARD in $BUILD_TYPE"
            echo "================================================================================="

            cmake -B build -G '${{matrix.env.gen}}' --fresh      \
              -D VULKAN_HPP_GENERATOR_BUILD=OFF                  \
              -D VULKAN_HPP_RUN_GENERATOR=OFF                    \
              -D VULKAN_HPP_SAMPLES_BUILD=OFF                    \
              -D VULKAN_HPP_TESTS_BUILD=ON                       \
              -D VULKAN_HPP_TESTS_CTEST=ON                       \
              -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON           \
              -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON       \
              -D VULKAN_HPP_PRECOMPILE=OFF                       \
              ${{matrix.env.modules && '-DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=d0edc3af-4c50-42ea-a356-e2862fe7a444' || ''}} \
              -D CMAKE_CXX_FLAGS=${{matrix.env.cxx_flags || ''}} \
              -D CMAKE_CXX_COMPILER=${{matrix.env.cxx}}          \
              -D CMAKE_CXX_STANDARD=$CXX_STANDARD                \
              -D CMAKE_BUILD_TYPE=$BUILD_TYPE
            cmake --build build --parallel --config $BUILD_TYPE --clean-first
            ctest -j --output-on-failure --test-dir build -C $BUILD_TYPE
          done
        done


