
name: CI Windows MSVC-MSBuild

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: ${{matrix.architecture}}

    - name: Generate headers
      run: |
        cmake -E time cmake -B build                   \
          -D VULKAN_HPP_GENERATOR_BUILD=ON             \
          -D VULKAN_HPP_RUN_GENERATOR=OFF              \
          -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
          -D VULKAN_HPP_TESTS_BUILD=OFF                \
          -D VULKAN_HPP_TESTS_CTEST=ON                 \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON     \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
          -D VULKAN_HPP_PRECOMPILE=OFF                 \
          -D CMAKE_CXX_STANDARD=20
        cmake -E time cmake --build build --parallel --config Debug
        cmake -E time cmake --build build --parallel --config Release

    - name: Build samples once
      run: |
        echo "================================================================================="
        echo "Building samples C++23 in Debug with architecture ${{matrix.architecture}}"
        echo "================================================================================="
        cmake -E time cmake -B build --fresh              \
          -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
          -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
          -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
          -D VULKAN_HPP_TESTS_BUILD=OFF                   \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
          -D VULKAN_HPP_PRECOMPILE=OFF                    \
          -D CMAKE_CXX_STANDARD=23
        cmake -E time cmake --build build --parallel --clean-first --config Debug

    - name: Build tests
      run: |
        for CXX_STANDARD in 11 14 17 20 23; do
          echo "================================================================================="
          echo "Building tests C++$CXX_STANDARD in Debug with architecture ${{matrix.architecture}}"
          echo "================================================================================="
          cmake -E time cmake -B build --fresh              \
            -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
            -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
            -D VULKAN_HPP_SAMPLES_BUILD=OFF                 \
            -D VULKAN_HPP_TESTS_BUILD=ON                    \
            -D VULKAN_HPP_TESTS_CTEST=ON                    \
            -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
            -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
            -D VULKAN_HPP_PRECOMPILE=OFF                    \
            -D CMAKE_CXX_STANDARD=$CXX_STANDARD
          cmake -E time cmake --build build --parallel --clean-first --config Debug
          ctest -j --output-on-failure --test-dir build -C Debug

          echo "================================================================================="
          echo "Building C++$CXX_STANDARD in Release with architecture ${{matrix.architecture}}"
          echo "================================================================================="
          cmake --build build --parallel --config Release
          ctest -j --output-on-failure --test-dir build -C Release
        done
 