
name: CI Windows ClangCL-Ninja

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.1.2
        ninjaVersion: latest
        
    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: ${{matrix.architecture}}

    - name: Generate headers
      run: |
        cmake -B build -G Ninja                        \
          -D VULKAN_HPP_GENERATOR_BUILD=ON             \
          -D VULKAN_HPP_RUN_GENERATOR=OFF              \
          -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
          -D VULKAN_HPP_TESTS_BUILD=OFF                \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON     \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
          -D VULKAN_HPP_PRECOMPILE=OFF                 \
          -D CMAKE_BUILD_TYPE=Debug                    \
          -D CMAKE_CXX_COMPILER=clang-cl               \
          -D CMAKE_CXX_STANDARD=20
        cmake --build build --parallel

        cmake -B build -G Ninja --fresh                \
          -D VULKAN_HPP_GENERATOR_BUILD=ON             \
          -D VULKAN_HPP_RUN_GENERATOR=ON               \
          -D VULKAN_HPP_SAMPLES_BUILD=OFF              \
          -D VULKAN_HPP_TESTS_BUILD=OFF                \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON     \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON \
          -D VULKAN_HPP_PRECOMPILE=OFF                 \
          -D CMAKE_BUILD_TYPE=Release                  \
          -D CMAKE_CXX_COMPILER=clang-cl               \
          -D CMAKE_CXX_STANDARD=20
        cmake --build build --parallel --clean-first

    - name: Build samples once
      run: |
        echo "================================================================================="
        echo "Building samples C++23 in Debug with architecture ${{matrix.architecture}}"
        echo "================================================================================="
        cmake -E time cmake -B build -G Ninja --fresh     \
          -D VULKAN_HPP_BUILD_CXX_MODULE=$CXX_MODULES     \
          -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
          -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
          -D VULKAN_HPP_SAMPLES_BUILD=ON                  \
          -D VULKAN_HPP_TESTS_BUILD=OFF                   \
          -D VULKAN_HPP_TESTS_CTEST=ON                    \
          -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
          -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
          -D VULKAN_HPP_PRECOMPILE=OFF                    \
          -D CMAKE_BUILD_TYPE=Debug                       \
          -D CMAKE_C_COMPILER=clang-cl                    \
          -D CMAKE_CXX_COMPILER=clang-cl                  \
          -D CMAKE_CXX_STANDARD=23                        \
          -D CMAKE_EXPERIMENTAL_CXX_IMPORT_STD=d0edc3af-4c50-42ea-a356-e2862fe7a444
        cmake -E time cmake --build build --parallel --clean-first

    - name: Build tests
      run: |
        for CXX_STANDARD in 11 14 17 20 23; do
          for BUILD_TYPE in Debug Release; do

            CXX_MODULES=ON
            if [ $CXX_STANDARD -lt 23 ]; then
              CXX_MODULES=OFF
            fi

            echo "================================================================================="
            echo "Building tests C++$CXX_STANDARD in $BUILD_TYPE with architecture ${{matrix.architecture}}"
            echo "================================================================================="

            cmake -B build -G Ninja --fresh                   \
              -D VULKAN_HPP_BUILD_CXX_MODULE=$CXX_MODULES     \
              -D VULKAN_HPP_GENERATOR_BUILD=OFF               \
              -D VULKAN_HPP_RUN_GENERATOR=OFF                 \
              -D VULKAN_HPP_SAMPLES_BUILD=OFF                 \
              -D VULKAN_HPP_TESTS_BUILD=ON                    \
              -D VULKAN_HPP_TESTS_CTEST=ON                    \
              -D VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=ON        \
              -D VULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON    \
              -D VULKAN_HPP_PRECOMPILE=OFF                    \
              -D CMAKE_BUILD_TYPE=$BUILD_TYPE                 \
              -D CMAKE_C_COMPILER=clang-cl                    \
              -D CMAKE_CXX_COMPILER=clang-cl                  \
              -D CMAKE_CXX_STANDARD=$CXX_STANDARD             \
              -D CMAKE_EXPERIMENTAL_CXX_IMPORT_STD=d0edc3af-4c50-42ea-a356-e2862fe7a444
            cmake --build build --parallel --clean-first
            ctest -j --output-on-failure --test-dir build
          done
        done
